# Generated by Django 5.0 on 2024-02-22 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateurs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField()),
                ('role', models.CharField(choices=[('role1', 'Simple'), ('role2', 'Chef')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('location', models.CharField()),
                ('telephone', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expediteur', models.CharField()),
                ('objet', models.CharField()),
                ('text', models.TextField()),
                ('date_envoi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_Acc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField()),
                ('acc_pass', models.CharField()),
                ('social_media', models.CharField(choices=[('social1', 'Facebook'), ('social2', 'Instagram'), ('social3', 'Linkedin')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image_msg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('mail_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_app.mail')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdf', models.FileField(upload_to='documents/')),
                ('mail_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_app.mail')),
            ],
        ),
        migrations.CreateModel(
            name='Voice_msg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='audio/')),
                ('mail_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_app.mail')),
            ],
        ),
    ]
