# Generated by Django 5.0 on 2024-02-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_app', '0002_alter_administrateurs_username_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrateurs',
            new_name='Administrateur',
        ),
    ]
